src/main/java/com/siegedog/knights/models/user/User.java
package com.siegedog.knights.models.user;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.siegedog.knights.gameplay.CombatEntity;
import com.siegedog.knights.models.characterclass.CharacterClass;
import com.siegedog.knights.models.items.Item;

@Entity
@Table(name = "users")
public class User implements CombatEntity {
	private static int[] LEVELS = new int[] {
		0,
		0,
		50,
		120,
		200,
		300,
		450,
		600,
		800,
		1100,
		1500,
		2000,
		2500,
		3000,
		3500,
		4000,
		4500,
		5000,
		6000,
		7000,
		8000,
		9000
	};
	
	@Id @GeneratedValue
	private Long id;
	
	private String name;
	private String password_hash;
	private String role;
	private Date registered_date;

	private Integer energy;
	private Integer gold;
	private Integer xp;
	
	@ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinTable(
		name = "items_users", 
		joinColumns = {	@JoinColumn(name = "id_user", nullable = false, updatable = true) }, 
		inverseJoinColumns = { @JoinColumn(name = "id_item", nullable = false, updatable = true) })
	private Set<Item> items;
	
	@ManyToOne
	@JoinColumn(name = "class", referencedColumnName = "id")
	private CharacterClass characterClass;
	
	// Used in combat simulations
	@Transient
	private Integer currentHealth;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String getPassword_hash() {
		return password_hash;
	}

	public void setPassword_hash(String password_hash) {
		this.password_hash = password_hash;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Integer getEnergy() {
		return energy;
	}

	public void setEnergy(Integer energy) {
		this.energy = energy;
	}

	public Integer getGold() {
		return gold;
	}

	public void setGold(Integer gold) {
		this.gold = gold;
	}

	public Integer getXp() {
		return xp;
	}

	public void setXp(Integer xp) {
		this.xp = xp;
	}

	public Long getId() {
		return id;
	}

	public Date getRegistered_date() {
		return registered_date;
	}
	
	public CharacterClass getCharacterClass() {
		return characterClass;
	}

	public void setCharacterClass(CharacterClass characterClass) {
		this.characterClass = characterClass;
	}

	public Set<Item> getItems() {
		return items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	public int getLevel() {
		int lvl = Arrays.binarySearch(LEVELS, getXp());
		if(lvl < 0) {
			lvl = (-lvl) - 1;
		}
		return lvl;
	}
	
	public Integer getCurrentHealth() {
		return currentHealth;
	}

	public void setCurrentHealth(Integer currentHealth) {
		this.currentHealth = currentHealth;
	}
	
	public Integer getMaxHealth() {
		int lvl = getLevel();
		return characterClass.getBase_health() + lvl * characterClass.getLvl_health();
	}
	
	public Integer getAttack() {
		int lvl = getLevel();
		return characterClass.getBase_attack() + lvl * characterClass.getLvl_attack();
	}
	
	public Integer getDefense() {
		int lvl = getLevel();
		return characterClass.getBase_defense() + lvl * characterClass.getLvl_defense();
	}

	@Override
	public void initCombat() {
		currentHealth = getMaxHealth();
	}
}

src/main/java/com/siegedog/knights/controller/MessageController.java
package com.siegedog.knights.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.siegedog.knights.models.mesaj.MesajBo;
import com.siegedog.knights.models.user.UserBo;

@Controller
public class MessageController {

	@Autowired MesajBo mesajBo;
	
	@RequestMapping(value = "/message", method = RequestMethod.POST)
	public ModelAndView showMessages(Model model) {
		System.out.println();
		ModelAndView modelAndView = new ModelAndView();
		modelAndView.setViewName("message");
		modelAndView.addObject("messages", "mess!");
		System.out.println(mesajBo.findAll().toArray().toString());
		return modelAndView;
	}
	

	@RequestMapping(value = "/", method = RequestMethod.POST)
	public ModelAndView sendMessage(ModelAndView modelAndView) {
		System.out.println();
		modelAndView.setViewName("message");
		modelAndView.addObject("messages", "mess!");
		System.out.println(mesajBo.findAll().toArray().toString());
		return modelAndView;
	}
}

src/main/webapp/WEB-INF/jsp/arena.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<c:import url="header.jsp" />

<h1>Arena fight</h1>
<c:choose>
<c:when test="${enemy != null}">
	<p>Fighting: ${enemy.name} (level ${enemy.level})</p>
	<c:import url="list-events.jsp" />
	
	<form action="/arena" method="post" role="form">
		<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
		<a href="/dashboard"><button type="button" role="button" class="btn btn-default btn-lg">Back to dashboard!</button></a>
		<button type="submit" role="button" name="submit" class="btn btn-primary btn-lg">Fight again! (1 energy)</button>
	</form>
</c:when>
<c:otherwise>
	<p>No matching enemies found...</p>
</c:otherwise>
</c:choose>

<c:import url="footer.jsp" />

src/main/webapp/WEB-INF/jsp/dashboard.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<c:import url="header.jsp" />

<h1>Welcome to the user dashboard, <c:out value="${user.name}" />!</h1>
<table class="table">
	<tr><td>Gold:</td><td>${user.gold}</td></tr>
	<tr><td>Level:</td><td>${user.level}</td></tr>
	<tr><td>Class:</td><td>${user.characterClass.name}</td></tr>
	<tr>
		<td>Items:</td>
		<td>
			<c:choose>
				<c:when test="${user.items.size() > 0}">
					<ul class="list-unstyled">
					<c:forEach var="i" items="${user.items}">
						<li>${i.name}</li>
					</c:forEach>
					</ul>
				</c:when>
				<c:otherwise>
					none
				</c:otherwise>
			</c:choose>	
		</td>
	</tr>
</table>

<div>
	<h2>Actions</h2>
	
	<form action="arena" method="post" role="form">
		<div class="form-group">
			<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
			<button type="submit" role="button" class="btn btn-primary btn-lg">Fight in the arena (1 Energy)</button>
		</div>
	</form>
	<form action="forest" method="post" role="form">
		<div class="form-group">
			<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
			<button type="submit" role="button" class="btn btn-primary btn-lg">Explore the forest (5 Energy)</button>
		</div>
	</form>
</div>

<c:import url="message.jsp" />

<c:import url="footer.jsp" />

src/main/webapp/WEB-INF/jsp/forest.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<c:import url="header.jsp" />

<h1>Exploring the forest!</h1>
<c:import url="list-events.jsp" />
	
<form action="/forest" method="post" role="form">
	<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
	<a href="/dashboard"><button type="button" role="button" class="btn btn-default btn-lg">Back to dashboard!</button></a>
	<button type="submit" role="button" name="submit" class="btn btn-primary btn-lg">Explore a different path! (5 energy)</button>
</form>

<c:import url="footer.jsp" />

src/main/webapp/WEB-INF/jsp/home.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<c:import url="header.jsp" />

<h1>Knights Wanted for Unusual Quests</h1>

<div>
<p>
	The island of <strong>Generica</strong> has sent word to every city in the kingdom of <strong>Arpegia</strong> that
	it's facing various issues with the indigenous monsters and traders, and that only brave questing adventurers can
	help its development (somehow).
</p>
<p>
	Join the crowd and become a hero today! <a href="/register">Sign up</a> or <a href="/login">sign in</a> to join the fun!
</p>
<p>
	<strong>Caution:</strong> this game is not particularily entertaining.
</p>
</div>

<c:import url="footer.jsp" />

src/main/webapp/WEB-INF/jsp/list-events.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<c:forEach var="evt" items="${combat.events}">
	<c:choose>
		<c:when test="${evt.type == 'ROUND'}">
			<h3>${evt.text}</h3>
		</c:when>
		<c:when test="${evt.type == 'STORY'}">
			<p class="story">${evt.text}</p>
		</c:when>
		<c:when test="${evt.type == 'VICTORY'}">
			<h2 class="victory">${evt.text}</h2>
		</c:when>
		<c:when test="${evt.type == 'DEFEAT'}">
			<h2 class="defeat">${evt.text}</h2>
		</c:when>
		<c:when test="${evt.type == 'ENEMYHEAL' }">
			<p class="enemy-heal">${evt.text}</p>
		</c:when>
		<c:otherwise>
			<p>${evt.text}</p>
		</c:otherwise>
	</c:choose>
</c:forEach>

src/main/webapp/WEB-INF/jsp/login.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@taglib prefix="sec" uri="http://www.springframework.org/security/tags"%>

<%@ page session="true" %>

<c:import url="header.jsp"></c:import>

<h1>Login</h1>

<div id="login-box"> 
	<c:if test="${not empty error}">
		<div class="alert alert-danger">${error}</div>
	</c:if>
	<c:if test="${not empty msg}">
		<div class="alert alert-info">${msg}</div>
	</c:if>
	
	<c:url value="/j_spring_security_check" var="loginUrl" />
	
	<form name='loginForm' action="${loginUtl}" method="post" role="form">
			<div class="form-group">
				<label for="username" class="form-label">Name:</label>
				<input type="text" name="username" id="username" class="form-control" />
			</div>
			
			<div class="form-group">
				<label for="password" class="form-label">Password:</label>
				<input type="password" name="password" id="password" class="form-control" />
			</div>
		  
	  	<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
	  	
	  	<button type="submit" role="button" class="btn btn-lg btn-primary">Login!</button>
	</form>
</div>

src/main/webapp/WEB-INF/jsp/message.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<h1>Messaging</h1>

<h2>Compose a message</h2>
<form name='messageForm' action="/message" method="post" role="form">
	<div class="form-group">
		<label for="user" class="form-label">Name:</label>
		<input type="text" name="user" id="user" class="form-control" />
	</div>

	<div class="form-group">
		<label for="msg" class="form-label">Message:</label> 
		<textarea name="msg" id="msg" class="form-control"></textarea>
	</div>

	<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />

	<button type="submit" role="button" class="btn btn-lg btn-primary">Send message!</button>
</form>

<h2>Received messages:</h2>

<c:choose>
	<c:when test="${messages.size() > 0}">
		<c:forEach var="m" items="${messages}">
			<div>From: <strong>${m.sender.name}</strong></div>
			<div>${m.msg}</div>
			<hr/>
		</c:forEach>
	</c:when>
	<c:otherwise>
		<div>No messages.</div>
	</c:otherwise>
</c:choose>

src/main/webapp/WEB-INF/jsp/register.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<c:import url="header.jsp" />

<h1>Registration</h1>

<c:if test="${br.hasErrors()}">
	<div class="alert alert-danger">
	   <ul class="list-unstyled">
	      <c:forEach var="error" items="${br.allErrors}">
	         <li><spring:message code="${error.code}"></spring:message></li>
	      </c:forEach>
	   </ul>
	</div>
</c:if>

<form action="/register" method="post" role="form">
	<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
	  	
	<div class="form-group">
		<label for="name" class="form-label">Username:</label>
		<input type="text" name="name" id="name" class="form-control" /> 
	</div>
	
	<div class="form-group">
		<label for="password" class="form-label">Password:</label>
		<input type="password" name="password" id="password" class="form-control" /> 
	</div>
	
	<div class="form-group">
		<label for="passwordconf" class="form-label">Password confirmation:</label>
		<input type="password" name="passwordconf" id="passwordconf" class="form-control" /> 
	</div>
	
	<div class="form-group">
		<label for="characterclass" class="form-label">Class:</label>
		<select name="characterclass" id="characterclass" class="form-control">
			<c:forEach var="cls" items="${classes}">
				<option value="${cls.id}">${cls.name}</option>
			</c:forEach>
		</select>
	</div>

	<a href="/"></a><button type="button" class="btn btn-default btn-lg">Back</button></a>
	<button type="submit" name="submit" class="btn btn-primary btn-lg">Register!</button>
</form>

<c:import url="footer.jsp" />

src/main/webapp/WEB-INF/jsp/roster.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<c:import url="header.jsp" />

<h1>Roster of enemies</h1>

<table class="table table-striped">
<tr>
	<th>Name</th>
	<th>Level</th>
	<th>Health Points</th>
	<th>Attack</th>
	<th>Defense</th>
</tr>
<c:forEach var="e" items="${enemies}">
	<tr>
		<td>${e.name}</td>
		<td>${e.level}</td>
		<td>${e.max_health}</td>
		<td>${e.attack}</td>
		<td>${e.defense}</td>
	</tr>
</c:forEach>
</table>

<c:import url="footer.jsp" />

src/main/webapp/WEB-INF/jsp/store.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>

<c:import url="header.jsp" />

<h1>Welcome to the shop</h1>

<table class="table table-striped">
<tr>
	<th>Name</th>
	<th>Bonuses</th>
	<th>Buy</th>
</tr>
<c:forEach var="i" items="${items}">
	<tr>
		<td><p>${i.name}</p><p class="small">${i.description}</p></td>
		<td>
			<c:if test="${i.attackbonus > 0}">
			+${i.attackbonus} Attack
			</c:if>
			<c:if test="${i.defensebonus > 0}">
			+${i.defensebonus} Defense
			</c:if>
			<c:if test="${i.healthbonus > 0}">
			+${i.healthbonus} Health
			</c:if>
		</td>
		<td>
			<form action="/store" method="post" role="form">
				<input type="hidden" name="item-id" value="${i.id}" />
				<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
				<button type="submit" class="btn btn-primary">Cost: ${i.value}</button>
			</form>
		</td>
	</tr>
</c:forEach>
</table>

<c:import url="footer.jsp" />